GET http://localhost:3000

### SEND FETCH LOCATION REQUEST
GET http://localhost:3000/location

### Find LOCATION REQUEST
GET http://localhost:3000/location/2

### Create New LOCATION REQUEST
POST http://localhost:3000/location
Content-Type: application/json

{
  "building": "A",
  "locationName": "Lobby Level1",
  "locationNumber": "A-01-Lobby",
  "area": "80.620",
  "parentId": 1
}

### Update LOCATION REQUEST
PUT http://localhost:3000/location/2
Content-Type: application/json

{
 "id": 2,
 "building": "A",
 "locationName": "Lobby Level1",
 "locationNumber": "A-01-Lobby",
 "area": "80"
}

### Update LOCATION REQUEST
DELETE http://localhost:3000/location/2
