GET http://localhost:3000

### SEND FETCH LOCATION REQUEST
GET http://localhost:3000/location

### Find LOCATION REQUEST
GET http://localhost:3000/location/2

### Create New LOCATION REQUEST
POST http://localhost:3000/location
Content-Type: application/json

{
  "building": "B",
  "locationName": "Lobby Level1",
  "locationNumber": "B-05-11-111",
  "area": 80.620,
  "parentId": 4
}

### Update LOCATION REQUEST
PUT http://localhost:3000/location/3
Content-Type: application/json

{
  "building": "B",
  "locationName": "Lobby Level1",
  "locationNumber": "B-05-11-111",
  "area": 80.620,
  "parentId": 10
}

### Update LOCATION REQUEST
DELETE http://localhost:3000/location/2
